spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate configurado para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Segredo fixo para o JWT não falhar na inicialização do SecurityFilter
api.security.token.secret=chave_de_teste_com_pelo_menos_32_caracteres_aleatorios

# DESATIVE o seeder nos testes para evitar erros de duplicidade ou falta de contexto
spring.sql.init.mode=never